[package]
name = "api"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
#dioxus = { workspace = true, features = ["server"] }
serde = {workspace = true, features = ["derive"]}
serde_json = {workspace = true}
anyhow = {workspace = true}